#!/usr/bin/env python3
"""
Migrate hashnode JSON backup to Astro markdown files.

For each published post:
  - Creates src/content/blog/<slug>/index.md
  - Copies images from hashnode_assets/posts/<id>/ to src/content/blog/<slug>/
  - Converts hashnode-specific markdown syntax to standard markdown/HTML

Conversions:
  - ![alt](url align="center") -> <img src="url" alt="alt" class="img-center" />
  - ![alt](url align="left")   -> <img src="url" alt="alt" class="img-left" />
  - Clickable image variants handled too
  - %[url] embeds -> inline links or YouTube iframes
  - {%- # TOC ... -%} liquid tags -> stripped
"""

import json
import re
import shutil
from pathlib import Path

BACKUP_DIR = Path("../hashnode-backup")
ASSETS_DIR = BACKUP_DIR / "hashnode_assets" / "posts"
CONTENT_DIR = Path("src/content/blog")
BACKUP_JSON = BACKUP_DIR / "hashnode_complete_backup.json"


def convert_image_align(md: str) -> str:
    """
    Convert hashnode image alignment syntax to raw HTML img tags.
    Handles:
      ![alt](url align="left|center")
      [![alt](url align="left|center")](link)
    """
    # Clickable image: [![alt](url align="...")](link)
    def replace_linked_img(m):
        alt = m.group(1)
        url = m.group(2)
        align = m.group(3).lower()
        link = m.group(4)
        css_class = f"img-{align}"
        return f'<a href="{link}"><img src="{url}" alt="{alt}" class="{css_class}" /></a>'

    md = re.sub(
        r'\[!\[([^\]]*)\]\(([^\s)]+)\s+align="(\w+)"\)\]\(([^)]+)\)',
        replace_linked_img,
        md,
    )

    # Plain image: ![alt](url align="...")
    def replace_img(m):
        alt = m.group(1)
        url = m.group(2)
        align = m.group(3).lower()
        css_class = f"img-{align}"
        return f'<img src="{url}" alt="{alt}" class="{css_class}" />'

    md = re.sub(
        r'!\[([^\]]*)\]\(([^\s)]+)\s+align="(\w+)"\)',
        replace_img,
        md,
    )

    return md


def convert_embeds(md: str) -> str:
    """
    Convert hashnode %[url] embeds.
    YouTube -> <iframe> embed
    Everything else -> plain markdown link
    """
    def replace_embed(m):
        url = m.group(1)
        # YouTube
        yt = re.match(
            r'https?://(?:www\.)?youtube\.com/watch\?v=([\w-]+)|'
            r'https?://youtu\.be/([\w-]+)',
            url,
        )
        if yt:
            vid_id = yt.group(1) or yt.group(2)
            return (
                f'<div class="embed-youtube">'
                f'<iframe src="https://www.youtube-nocookie.com/embed/{vid_id}" '
                f'frameborder="0" allowfullscreen></iframe>'
                f'</div>'
            )
        # Default: plain link
        return f'[{url}]({url})'

    return re.sub(r'%\[([^\]]+)\]', replace_embed, md)


def strip_liquid_toc(md: str) -> str:
    """Remove {%- # TOC ... -%} tags generated by hashnode."""
    return re.sub(r'\{%-?\s*#.*?-?%\}\n?', '', md)


def rewrite_image_paths(md: str, slug: str, post_id: str) -> str:
    """
    Rewrite CDN image URLs that were downloaded locally to relative paths.
    The downloaded images are in hashnode_assets/posts/<id>/ with their
    original filename (last path segment of the CDN URL).
    """
    local_assets = ASSETS_DIR / post_id
    if not local_assets.exists():
        return md

    downloaded = {f.name: f for f in local_assets.iterdir() if f.is_file()}
    if not downloaded:
        return md

    def maybe_rewrite(url: str) -> str:
        filename = url.split("/")[-1].split("?")[0]
        if filename in downloaded:
            return f"./{filename}"
        return url

    # Rewrite in standard markdown images
    def rewrite_md_img(m):
        alt = m.group(1)
        url = maybe_rewrite(m.group(2))
        return f"![{alt}]({url})"

    md = re.sub(r'!\[([^\]]*)\]\(([^)\s]+)\)', rewrite_md_img, md)

    # Rewrite in HTML img tags (after align conversion)
    def rewrite_html_src(m):
        before = m.group(1)
        url = maybe_rewrite(m.group(2))
        after = m.group(3)
        return f'{before}{url}{after}'

    md = re.sub(r'(src=")([^"]+)(")', rewrite_html_src, md)

    return md


def yaml_str(value: str) -> str:
    """Wrap a string in double quotes with proper YAML escaping."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_frontmatter(post: dict, has_local_cover: bool) -> str:
    title = post["title"]
    description = (
        post.get("seo", {}).get("description")
        or post.get("brief")
        or ""
    )
    pub_date = post["publishedAt"][:10]
    updated_date = (post.get("updatedAt") or "")[:10]

    tags = [t["slug"] for t in (post.get("tags") or [])]

    lines = [
        "---",
        f"title: {yaml_str(title)}",
        f"description: {yaml_str(description)}",
        f"pubDate: '{pub_date}'",
    ]
    if updated_date and updated_date != pub_date:
        lines.append(f"updatedDate: '{updated_date}'")

    cover = post.get("coverImage") or {}
    cover_url = cover.get("url", "")
    if cover_url:
        if has_local_cover:
            cover_filename = cover_url.split("/")[-1].split("?")[0]
            lines.append(f"heroImage: './{cover_filename}'")
        else:
            lines.append(f"heroImage: {yaml_str(cover_url)}")

    read_time = post.get("readTimeInMinutes")
    if read_time:
        lines.append(f"readTime: {read_time}")

    if tags:
        lines.append(f"tags: [{', '.join(repr(t) for t in tags)}]")

    lines.append("---")
    return "\n".join(lines)


def migrate_post(post: dict):
    slug = post["slug"]
    post_id = post["id"]
    out_dir = CONTENT_DIR / slug
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy local assets
    src_assets = ASSETS_DIR / post_id
    has_local_cover = False
    if src_assets.exists():
        cover_url = (post.get("coverImage") or {}).get("url", "")
        cover_filename = cover_url.split("/")[-1].split("?")[0] if cover_url else ""
        for f in src_assets.iterdir():
            if f.is_file():
                shutil.copy2(f, out_dir / f.name)
                if f.name == cover_filename:
                    has_local_cover = True

    # Process markdown
    md = post["content"].get("markdown") or ""
    md = strip_liquid_toc(md)
    md = convert_image_align(md)
    md = convert_embeds(md)
    md = rewrite_image_paths(md, slug, post_id)

    frontmatter = build_frontmatter(post, has_local_cover)

    (out_dir / "index.md").write_text(f"{frontmatter}\n\n{md}\n", encoding="utf-8")
    print(f"  ✓ {slug}")


def main():
    with open(BACKUP_JSON, encoding="utf-8") as f:
        data = json.load(f)

    posts = data["publications"][0]["posts"]
    print(f"Migrating {len(posts)} posts...")

    CONTENT_DIR.mkdir(parents=True, exist_ok=True)

    # Remove sample posts from template
    for sample in CONTENT_DIR.glob("*.md"):
        sample.unlink()
    for sample in CONTENT_DIR.glob("*.mdx"):
        sample.unlink()

    for post in sorted(posts, key=lambda p: p["publishedAt"]):
        migrate_post(post)

    print(f"\nDone. Output: {CONTENT_DIR}/")


if __name__ == "__main__":
    main()
